services:
  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: veda-scraper
    environment:
      - VALIDATION_KEY=password
      - BASE_URL=http://baseurl/
    volumes:
      - hmc_run:/root/.minecraft
      - hmc_auth:/minecraft/HeadlessMC/auth
    restart: no

volumes:
  hmc_run:
  hmc_auth:
