services:
  scraper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: veda-scraper
    env_file: ./.env
    volumes:
      - hmc_run:/root/.minecraft
      - hmc_auth:/minecraft/HeadlessMC/auth
    networks:
      - shared
    restart: no

volumes:
  hmc_run:
  hmc_auth:

networks:
  shared:
    external: true
